POST http://localhost:8080/payments
Content-Type: application/json

{
  "correlationId": "688b5eed-c7fb-46f1-9ca0-d1a3651e174e",
  "amount": 1500.00
}
###

GET http://localhost:8080/payments-summary
###

GET http://localhost:8080/payments-summary?from=2025-08-11T16:38:59.506Z&to=2025-08-11T16:39:13.006Z
###

GET http://localhost:8001/admin/payments-summary
X-Rinha-Token: 123
###

GET http://localhost:8001/admin/payments-summary?from=2025-08-11T16:38:59.506Z&to=2025-08-11T16:39:13.006Z
X-Rinha-Token: 123
###